In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

# 💙리스트로 배열 만들기

In [3]:
al = np.array([1,2,3,4,5])
print(type(al))
print(al.shape) # 5개의 element가 있다. / 쉼표 뒤에 아무것도 없으니 1차원 배열이구나
print(al[0],al[1],al[2],al[3],al[4])
al[0] = 10
al[1] = 9
al[2] = 8
print(al)

<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[10  9  8  4  5]


In [4]:
# 2차원
a2 = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,2]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2]) # 인덱스 접근을 해서 자료를 살펴볼수 있다.

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
(3, 4)
1 5 9


In [5]:
# 3차원
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


# 💛배열 생성 및 초기화

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
print(np.ones(10))
print(np.ones((3,3))) # shape모양을 넣어주는 것으로 2차원가능

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
np.full((5,3),2.39) # 모든 요소를 지정한 값으로 초기화

array([[2.39, 2.39, 2.39],
       [2.39, 2.39, 2.39],
       [2.39, 2.39, 2.39],
       [2.39, 2.39, 2.39],
       [2.39, 2.39, 2.39]])

In [9]:
np.eye(3) # 주대각선의 원소가 1이고 나머지 원소는 모두 0인 정사각 행렬(단위행렬)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.tri(3) # 삼각행렬

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [11]:
np.empty(10) 
# 초기화 되지 않은 배열 생성
# 초기화 하지 않기 때문에 어떤 배열보다 빠르게 배열생성
# 기존 메모리 위치에 존재하는 값이 들어가있기 때문에 기존의 값이 들어감 랜덤하다.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
print(al.shape)
np.zeros_like(al)  # al의 shape과 같은 모양으로 0이 채워진 배열을 하나 만들어줘

(5,)


array([0, 0, 0, 0, 0])

In [13]:
np.ones_like(a2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
print(a3.shape)
np.full_like(a3,10)

(3, 3, 3)


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

# 🧡생성한 값으로 배열생성

In [15]:
np.arange(0,30,2) # 정수 범위로 배열 생성 / 파이썬의 range와 비슷 똑같

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
np.linspace(0,1,5) # 범위 내에서 균등 간격의 배열 생성

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.logspace(0.1,1,20) # 범위 내에서 균등간격으로 로그 스케일로 배열 생성

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

# 💚랜덤 값으로 배열 생성

In [18]:
np.random.random((3,3)) # 랜덤한 수의 배열 생성 / 실수 반환 / shape만 주면됌

array([[0.12571503, 0.93709544, 0.72009053],
       [0.41245299, 0.15015162, 0.353426  ],
       [0.53374232, 0.83683487, 0.99498889]])

In [19]:
np.random.randint(1,20,(3,3)) # 일정 범위 지정해주고 shape의 랜덤 정수의 배열생성

array([[ 6,  2, 12],
       [15, 15, 17],
       [12, 12, 17]])

In [20]:
np.random.normal(0,1,(3,3)) #  정규분포를 고려한 랜덤한 수의 배열 생성

array([[-0.03623518, -0.07164097,  0.16784686],
       [-0.43953571, -1.41542816,  0.53601796],
       [-0.93882856, -1.10971912, -1.5218221 ]])

In [21]:
np.random.rand(3,3) # 균등분포를 고려한 랜덤한 수의 배열 생성

array([[0.1616046 , 0.4385019 , 0.65772016],
       [0.17082224, 0.96935429, 0.56781741],
       [0.96109924, 0.72538972, 0.65130089]])

In [22]:
np.random.randn(3,3) # 표준정규분포를 고려한 랜덤한 수의 배열

array([[-1.56728219, -1.27063016, -1.0829763 ],
       [-0.78910159,  1.01328576,  0.32420338],
       [ 0.91900967, -0.14338816, -2.38501375]])

# 💜표준 데이터 타입

In [23]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
np.full((3,3),1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 🖤날짜/시간 배열 생성 

In [26]:
date = np.array('2021-09-15', dtype=np.datetime64) # 날짜시간을 나타내주는 dtype
date

array('2021-09-15', dtype='datetime64[D]')

In [27]:
date + np.arange(12) # 0~11이 날짜에 더해짐

array(['2021-09-15', '2021-09-16', '2021-09-17', '2021-09-18',
       '2021-09-19', '2021-09-20', '2021-09-21', '2021-09-22',
       '2021-09-23', '2021-09-24', '2021-09-25', '2021-09-26'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64('2020-09-15 12:00')
datetime

numpy.datetime64('2020-09-15T12:00')

In [29]:
datetime2 = np.datetime64('2020-09-15 12:00:12.34','ns')
datetime2

numpy.datetime64('2020-09-15T12:00:12.340000000')

# 💚배열 속성 정보

In [30]:
def array_info(array):
    print(array) # 실재 배열의 값
    print("ndim :", array.ndim) # 1차원, 2차원
    print("shape :", array.shape) # 엘리먼트 모양
    print("dtype :", array.dtype) # 데이터 타입
    print("size :", array.size) # 엘리먼트들의 개수
    print("itemsize :", array.itemsize) # 각 하나의 아이템이 가지는 사이즈
    print("nbytes :", array.nbytes) # size * itemsize 전체 바이트
    print("strides :", array.strides) #  다음으로 넘어가기 위한 사이즈 단위

In [31]:
array_info(al)

[10  9  8  4  5]
ndim : 1
shape : (5,)
dtype : int32
size : 5
itemsize : 4
nbytes : 20
strides : (4,)


In [32]:
array_info(a2)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
ndim : 2
shape : (3, 4)
dtype : int32
size : 12
itemsize : 4
nbytes : 48
strides : (16, 4)


In [33]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim : 3
shape : (3, 3, 3)
dtype : int32
size : 27
itemsize : 4
nbytes : 108
strides : (36, 12, 4)


# 🟩인덱싱 

In [34]:
# 1차원
print(al)
print(al[0])
print(al[1])
print(al[2])
print(al[-3])
print(al[-1])

[10  9  8  4  5]
10
9
8
8
5


In [35]:
# 2차원
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[2,-1])
print(a2[2])


[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
1
3
2
[7 8 9 2]


In [36]:
# 3차원
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


# 💛슬라이싱 a[start:stop:step] / 기본값 start=0, stop=ndim, step=1
## array[(행 시작:끝), (열 시작:끝)]

In [37]:
print(al)
print(al[0:2])
print(al[0:])
print(al[:1])
print(al[::2])
print(al[::-1]) # reverse

[10  9  8  4  5]
[10  9]
[10  9  8  4  5]
[10]
[10  8  5]
[ 5  4  8  9 10]


In [38]:
print(a2)
print("2 >>>",a2[1])
print("3 >>>",a2[1,:])
print("4 >>>",a2[:2,:2])
print("5 >>>",a2[1:,::-1])
print("6 >>>",a2[::-1,::-1])

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
2 >>> [4 5 6 5]
3 >>> [4 5 6 5]
4 >>> [[1 2]
 [4 5]]
5 >>> [[5 6 5 4]
 [2 9 8 7]]
6 >>> [[2 9 8 7]
 [5 6 5 4]
 [4 3 2 1]]


# 💛불리언 인덱싱 
# True값인 인덱스만 조회 / 배열 각 요소의 선택여부를 불리언으로 조정

In [39]:
print(al)
bl = [False,True,True,False,True]
print(al[bl])
bl = [True,False,True,True,False]
print(al[bl])

[10  9  8  4  5]
[9 8 5]
[10  8  4]


In [40]:
print(a2)
b2 = np.random.randint(0,2,(3,4), dtype=bool) # 랜덤인데 인트로 해줘 근데 타입을 bool로
print(b2)
b2 = np.random.randint(0,2,(3,4), dtype=bool)
print(a2[b2])

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
[[ True  True False  True]
 [False  True  True  True]
 [ True False False False]]
[3 5 5 7 8]


# 💙팬시 인덱싱 

In [41]:
print(al) # 1차원 데이터
print(al[0],al[2])
ind = [0,2]
print(al[ind])
ind = np.array([[0,1],
               [2,0]])
print(al[ind]) # 1차원에 2차원인덱스를 넣었음>> 결과는 2차원으로 나옴

[10  9  8  4  5]
10 8
[10  8]
[[10  9]
 [ 8 10]]


In [42]:
print(a2) # 2차원 데이터
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1]) # row는 0, 2만, col은 1만  [2,8]
print(a2[2,col])

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
[2 9]
[[1 2 3 4]
 [7 8 9 2]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]


In [43]:
test = np.array([1, 2, 3, 4, 5])
test[[0, 2, 4]] # 0,2,4의 인덱스 값

array([1, 3, 5])

In [44]:
test2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

test2[[0, 2], 1:3] # 0, 2 행의 1~2 열의 내용을 가져오라

array([[2, 3],
       [8, 9]])

# 💜배열 값 삽입/수정/삭제/복사 

### 배열 값 삽입
* insert() : 특정 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가로 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열을 반환한다.

In [45]:
print(al)
bl = np.insert(al,0,7) # 0번째 위치에 10을 넣어줘
print(bl)
print(al) # bl 이라는 새로운 배열이 만들어진 것이다.
cl = np.insert(al,2,10)
print(cl)

[10  9  8  4  5]
[ 7 10  9  8  4  5]
[10  9  8  4  5]
[10  9 10  8  4  5]


In [46]:
print(a2)
b2 = np.insert(a2, 1, 7, axis=0) # 1번째 자리에 7을 넣어라, axis가 0이니 row축을 기준으로
print(b2)
c2 = np.insert(a2, 1, 7, axis=1) # 1번째 자리에 7을 넣어라, axis가 1이니 column축을 기준으로
print(c2)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
[[1 2 3 4]
 [7 7 7 7]
 [4 5 6 5]
 [7 8 9 2]]
[[1 7 2 3 4]
 [4 7 5 6 5]
 [7 7 8 9 2]]


### 배열 값 수정
* 배열의 인덱싱으로 접근하여 값 수정

In [47]:
print(al)
al[0] = 1
al[1] = 2
al[2] = 3
print(al)
al[:1] = 9
print(al)
i = np.array([1,3,4])
al[i] = 0
print(al)
al[i] += 4
print(al)

[10  9  8  4  5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [48]:
print(a2)
a2[0,0] =1
a2[1,1] =2
a2[2,2] =3
a2[0] =1
print(a2)
a2[1:,2] =9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 2]]
[[1 1 1 1]
 [4 2 6 5]
 [7 8 3 2]]
[[1 1 1 1]
 [4 2 9 5]
 [7 8 9 2]]
[[1 0 1 1]
 [4 2 0 5]
 [7 8 9 2]]


### 배열 값 삭제
* delete() : 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 return

In [49]:
print(al)
bl = np.delete(al,1)
print(bl)
print(al)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [50]:
print(a2)
b2 = np.delete(a2,1,axis=0) # 첫번재 row를 기준으로 
print(b2)
c2 = np.delete(a2,1,axis=1) # column을 기준으로 첫번째 제거
print(c2)

[[1 0 1 1]
 [4 2 0 5]
 [7 8 9 2]]
[[1 0 1 1]
 [7 8 9 2]]
[[1 1 1]
 [4 0 5]
 [7 9 2]]


### 배열 복사
* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [53]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2] # 동일한 메모리의 위치를 사용한다.
print(a2_sub)
a2_sub[:,1] =0
print(a2_sub)

print(a2)

[[1 0 1 1]
 [4 0 0 5]
 [7 8 9 2]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1 1]
 [4 0 0 5]
 [7 8 9 2]]


* copy() : 배열이나 하위 배열 내의 값을 명시적으로 복사

In [54]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1 1]
 [4 0 0 5]
 [7 8 9 2]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1 1]
 [4 0 0 5]
 [7 8 9 2]]


# 🤎배열 변환

### 배열 전치 및 축 변경

In [57]:
print(a2)
print(a2.T) # 행과 열이 바뀜

[[1 0 1 1]
 [4 0 0 5]
 [7 8 9 2]]
[[1 4 7]
 [0 0 8]
 [1 0 9]
 [1 5 2]]


In [58]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


### 배열 재구조화
* reshape() : 배열의 형상을 변경
* newaxis() : 새로운 축 추가

In [64]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3)) # 1차원이 2차원으로

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경
* 배열 모양만 변경

In [71]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[7 6 4 9 7]
 [9 3 1 8 8]]
[[7 6]
 [4 9]
 [7 9]
 [3 1]
 [8 8]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [72]:
n2.resize((5,5))
print(n2)

[[7 6 4 9 7]
 [9 3 1 8 8]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열크기감소
* 포함되지 않은 값은 삭제됨

In [73]:
n2.resize((3,3))
print(n2)

[[7 6 4]
 [9 7 9]
 [3 1 8]]


### 배열추가
* append() : 배열의 끝에 값 추가

In [75]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [76]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape는 같아야함

In [77]:
c2 = np.append(a2,b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape는 같아야함

In [78]:
c2 = np.append(a2,b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결
* concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [79]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [80]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [85]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* vstack() : 수직 스택 , 1차원으로 연결

In [83]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* hstack() : 수평스택, 2차원으로 연결

In [84]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* dstack() : 깊이스택, 3차원으로 연결

In [86]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* stack() : 새로운 차원으로 연결

In [88]:
np.stack([a2,a2]) # 2차원이 3차원으로

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할
* split() : 배열 분할

In [100]:
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5])
print(b1, c1)
b1, c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1, c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* vsplit(): 수직 분할, 1차원으로 분할

In [102]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* hsplit(): 수평 분할, 2차원으로 분할

In [104]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[1])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
[[2 3]
 [5 6]
 [8 9]]


* dsplit(): 수평 분할, 3차원으로 분할

In [110]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.hsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]
[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]
